### PR TITLE
Deprecated "OTU" in favor of "taxon"

### PR DESCRIPTION
**Pull request by qiyunzhu**
This PR removes the outdated term "OTU" from both documentation and code, and replaces it with the more generic term "taxon". As a consequence, the parameter `otu_ids` now becomes `taxa`. This affects `faith_pd`, `phydiv`, `unweighted_unifrac` and `weighted_unifrac`. The parameter `otu_ids` is kept as an alias of `taxa`, such that existing code that uses these functions will not break. A deprecation warning is displayed in the documentation.

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [x] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by wasade** [comment]
Hi @qiyunzhu, out of curiosity, what about `feature` instead as some of the calculations are not specific to taxa?

**Comment by qiyunzhu** [comment]
@wasade Thanks for the suggestion. I thought about "feature", but eventually thought that "taxon" is a more familiar term to people who study evolution and ecology. For example, we can call each tip in a phylogenetic tree as a "feature" but that doesn't sound intuitive. Some of my rationales can be found in #1902.

**Comment by wasade** [comment]
True, but in that case, we use the `TreeNode` for more than phylogenies. And, many of the diversity calculations are applicable to mass spectrometry data

**Comment by qiyunzhu** [comment]
I tend to think that "tree" may not be unintuitive to phylogeneticists. I agree that "taxon" does not have a broad meaning as "feature" does. To clarify that, the documentation has an explanation:

Previous verison:

```
We use the term "OTU" here very loosely, as these can in practice represent
diverse feature types including bacterial species, genes, and metabolites. The
term "sample" is also loosely defined for these purposes. These are intended to
represent a single unit of sampling, and as such what a single sample
represents can vary widely. For example, in a microbiome survey, these could
represent all 16S rRNA gene sequences from a single oral swab. In a comparative
genomics study on the other hand, a sample could represent an individual
organism's genome.
```

In this PR:
```
The term "taxon" (plural: "taxa") describes a group of biologically related
organisms that constitute a unit in the community. Taxa are usually defined at
a uniform taxonomic rank, such as species, genus or family. In community
ecology, taxon is usually referred to as "species" (singular = plural), but its
definition is not limited to species as a taxonomic rank. The term "taxonomic
group" is a synonym of taxon in many situations.

In scikit-bio, the term "taxon/taxa" is used very loosely, as these can in
practice represent diverse feature types including organisms, genes, and
metabolites. The term "sample" is also loosely defined for these purposes.
These are intended to represent a single unit of sampling, and as such what a
single sample represents can vary widely. For example, in a microbiome survey,
these could represent all 16S rRNA gene sequences from a single oral swab. In
a comparative genomics study on the other hand, a sample could represent an
individual organism's genome.
```

Regarding diversity calculation on non-community data: Currently, all alpha diversity metrics require input data to be counts (non-negative integers). This might be relaxed to accept floating-point numbers. For example, transcriptomic data in the unit of RPKM or TPM can use these functions too. Not all diversity metrics can accept floating-point numbers (for example, Chao1), but some do (for example, Shannon). This potential may be explored in scikit-bio.

**Comment by qiyunzhu** [comment]
@mataton Thanks for reviewing! I agree with your assessment of the two places in the documentation. I have fixed them and updated this pull request.

**Pull request merged**
