### PR TITLE
Fix `SampleMetadata` read/write on Windows

### PR DESCRIPTION
**Pull request by mataton**
This PR solves issue #2048. The issue was that Python's CSV writer will add blank lines between rows on windows if the `newline` parameter is not specified. 

See [here](https://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row) for more information.

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [ ] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by mataton** [comment]
@LarsHunger Your review would be appreciated as well.

**Review by qiyunzhu — APPROVED** [review]
@mataton and I spent quite some time navigating the I/O system of scikit-bio until finding this solution.

**Review by wasade — CHANGES_REQUESTED** [review]
Would it be possible to add a regression test for this?

**Comment by qiyunzhu** [comment]
@wasade This PR fixes a bug that previously didn't work but now works. The unit-tests that assess the output given the input were already implemented. Are there some other regression tests do you envison could be added?

**Comment by wasade** [comment]
Oh, I see. The test never passed on Windows -- thanks!

**Comment by LarsHunger** [comment]
> @LarsHunger Your review would be appreciated as well.

Don't know how much I can say, looks good to me!

**Pull request merged**
