### PR TITLE
Added NumPy 2.0 support

### PR DESCRIPTION
**Pull request by qiyunzhu**
Fixed the last few issues that block NumPy 2.0. Addressing #1964 .

Tested and working. Method:

```bash
> conda create -y -n skbio-np2 -c conda-forge python
> conda activate skbio-np2
> pip cache purge
> pip install numpy==2.0.0rc2 cython
> pip install biom-format --no-build-isolation
> echo "import biom; print(biom.__version__)" | python
2.1.16
> pip install requests decorator natsort
> pip install -e . --no-build-isolation
> echo "import skbio; print(skbio.__version__)" | python
0.6.1-dev
> pip install matplotlib pytest responses coverage
> python -m skbio.test
3000 passed
```

Note: The CI workflow hasn't been updated. It would make more sense to change it after NumPy 2.0 is formally released (due by Jun 16, 2024), and may benefit from another update of BIOM.

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [ ] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
Hi @mataton could you please try this to make sure it works in both Linux and Windows? Thanks!

**Comment by mataton** [comment]
@qiyunzhu Unfortunately it looks like quite a few things break in Windows while testing this PR with the environment set up as described. I'll test linux next. 

````
FAILED skbio/stats/distance/_mantel.py::skbio.stats.distance._mantel.mantel
FAILED skbio/stats/distance/tests/test_base.py::DissimilarityMatrixTests::test_filter_asymmetric - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DissimilarityMatrixTests::test_filter_duplicate_ids - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DissimilarityMatrixTests::test_filter_empty_ids - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DissimilarityMatrixTests::test_filter_missing_ids_strict_false - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DissimilarityMatrixTests::test_filter_reorder - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DissimilarityMatrixTests::test_filter_single_id - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DissimilarityMatrixTests::test_filter_subset - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DistanceMatrixTests::test_permute_condensed - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_base.py::DistanceMatrixTests::test_permute_not_condensed - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::InternalMantelTests::test_pearsonr_full - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::InternalMantelTests::test_perm_pearsonr3 - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::InternalMantelTests::test_perm_pearsonr6 - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::InternalMantelTests::test_perm_pearsonr_full - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::InternalMantelTests::test_spearmanr_full - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_comparing_same_matrices - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_distance_matrix_instances_as_input - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_distance_matrix_instances_with_lookup - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_distance_matrix_instances_with_reordering_and_nonmatching - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_negative_correlation - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_no_side_effects - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_one_sided_greater - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_one_sided_less - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_statistic_same_across_alternatives_and_permutations - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_two_sided - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::MantelTests::test_vegan_example - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_duplicate_dms - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_filepaths_as_input - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_id_lookup - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_many_filepaths_as_input - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_minimal_compatible_input - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_minimal_compatible_input_with_labels - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_mixed_input_types - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_reordered_distance_matrices - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::PairwiseMantelTests::test_strict - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::OrderDistanceMatricesTests::test_id_lookup - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::OrderDistanceMatricesTests::test_reordered_and_nonmatching_distance_matrices - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/distance/tests/test_mantel.py::OrderDistanceMatricesTests::test_reordered_distance_matrices - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/ordination/tests/test_principal_coordinate_analysis.py::TestPCoA::test_permutted - ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
FAILED skbio/stats/power.py::skbio.stats.power
````

All of these failures have to do with three functions in `skbio/stats/distance/_cutils.pyx`:  `distmat_reorder_cy`, `distmat_reorder_condensed_cy`, and `mantel_perm_pearsonr_cy`.

**Comment by mataton** [comment]
@qiyunzhu Everything passes on linux!

**Comment by qiyunzhu** [comment]
@mataton Thank you! This problem seems to be related to this [paragraph](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#windows-default-integer).

**Comment by qiyunzhu** [comment]
@mataton I am trying one of the plausible fixes. Can you test again? Thanks!

**Comment by qiyunzhu** [comment]
If this fails, we should revert the last commit, and try:

Add `ctypedef cnp.npy_intp intp_t` to the beginning of `skbio/stats/distance/_cutils.pyx`, then replace `long` with `intp_t`.

If this still fails, we should restore, and try:

In the Python code, before calling the Cython functions, do `arr = arr.astype("long", copy=False)`. For example, `distmat_reorder_cy(in_mat, np_reorder, out_mat)` becomes `distmat_reorder_cy(in_mat, np_reorder.astype("long", copy=False), out_mat)`.

**Comment by mataton** [comment]
The `dtype=np.intp` solution still fails. I'll try the `ctypedef cnp.npy_intp intp_t` solution now and let you know what happens.

**Comment by mataton** [comment]
@qiyunzhu Putting `ctypedef cnp.npy_intp intp_t` at the top of `skbio/stats/distance/_cutils.pyx` and replacing `long` with `intp_t` works!

**Comment by qiyunzhu** [comment]
@mataton Thanks for confirming! I updated the PR. Can you do another round of test to make sure that it works?

**Comment by mataton** [comment]
@qiyunzhu After an additional round of testing everything in this PR works on Windows and linux.

**Comment by qiyunzhu** [comment]
@mataton Given your finding in the other PR, may be you can test the code with Windows and NumPy 1.x to see if it works, and if not, re-applying the edit in commit [638b3ad](https://github.com/scikit-bio/scikit-bio/pull/2035/commits/638b3ad4c585638cfb9d6132bd5de38fac7fe416) in a new PR?

**Comment by mataton** [comment]
@qiyunzhu I've tested this, the changes currently in `main` (ie. the two PRs which have been merged) work on Windows, Mac, and linux with NumPy 1.x and NumPy 2.0. We are good to go across platforms and NumPy versions.

**Pull request merged**
