### PR TITLE
Elevated and added read parameters to sample metadata

### PR DESCRIPTION
**Pull request by qiyunzhu**
This PR does two things:

1) Adds `skbio.metadata.SampleMetadata` to `skbio/__init__.py`, such that the class can be imported by `from skbio import SampleMetadata`. Addresses #2055 .

2) Allows `SampleMetadata.read` to accept keyword arguments such as `default_missing_scheme`, which is useful when reading a structured metadata table. With this addition, one can do `SampleMetadata.read('metadata.tsv', default_missing_scheme='INSDC:missing')` or `skbio.io.read('metadata.tsv', into=SampleMetadata, default_missing_scheme='INSDC:missing')`

This patch makes `read` function like [`SampleMetadata.load`](https://scikit.bio/docs/latest/generated/skbio.metadata.SampleMetadata.load.html). In fact, the `load` method is not present in any other modules of skbio. It is likely an inheritance from q2. To make the skbio logic consistent, I would suggest deprecating `load` in favor of `read`. We can keep `load` as an alias to `read` for backward compatibility and compatibility with q2.

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [ ] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@mortonjt Do you have some thoughts on this?

**Comment by qiyunzhu** [comment]
@mataton What do you think of this PR?

**Comment by mataton** [comment]
@qiyunzhu This looks good to me. I agree with deprecating `load` in favor of `read`.

**Comment by qiyunzhu** [comment]
@mataton Sure! Thanks!

**Pull request merged**
