### PR TITLE
Garbage collection for Gzip functionality in Python 3.12

### PR DESCRIPTION
**Pull request by mataton**
This PR is a test to see if the garbage collection (`gc`) solution proposed by @actapia (See #1897) can function with Python 3.12. Another solution by @actapia is in #1928.

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/scikit-bio/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/scikit-bio/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@wasade @mortonjt Do you have any thoughts on this? I tend to think this solution is okay, and we should merge it to unblock Python 3.12, unless we know there are certain use cases where skbio may break. All unit tests pass. So if there is such a use case, it hasn't been tested yet.

**Comment by mortonjt** [comment]
I can't think of any edge cases where this will be a problem. 👍 on merge

**Comment by qiyunzhu** [comment]
@mataton Can you please document this change and acknowledge @actapia 's contribution in `CHANGELOG.md`? Thank you!

**Review by qiyunzhu — APPROVED** [review]
This looks good to me. Let's merge!

**Pull request merged**
