### PR TITLE
Modifying test_util to work in the windows environment

### PR DESCRIPTION
**Pull request by RaeedA**
Changing test_util to filter out extra occurrences of "\r" that appear in Windows systems, as well as modifying behavior between binary vs other tests. This removes all errors present in test_util.py.

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [x] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@RaeedA Good job! There is an unexpected linting issue. I am trying to fix it in #2069 . Once that one is merged, you can update your PR and re-activate CI workflow by:

```bash
git fetch upstream
git merge upstream/main
git push origin windows-test_util-fixes
```

I don't have Windows so I will leave it for @mataton to test.

**Comment by mataton** [comment]
Hey @RaeedA, good work! There is one more test which fails in a similar way in `skbio/io/tests/test_registry.py`. You can see the output of the test here:

````
(skbio-dev) C:\Users\maton\qlab\skbio\windows\github\scikit-bio>python skbio\io\tests\test_registry.py
...................................................................................F..........
======================================================================
FAIL: test_io_kwargs_passed (__main__.TestWrite.test_io_kwargs_passed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\tests\test_registry.py", line 1720, in test_io_kwargs_passed
    self.assertEqual(expected, fh.read())
AssertionError: b'BZh91AY&SY\x03\x89\x0c\xa6\x00\x00\x01\xc1\x00\x00\[57 chars]\x00' != b'BZh91AY&SY@\x95Dx\x00\x00\x03A\x00\x00\x128\x00 \x0[45 chars]\x00'

----------------------------------------------------------------------
Ran 94 tests in 0.326s

FAILED (failures=1)
````

Once you fix this additional test and merge the latest changes from the main branch into your `windows-test_util-fixes` branch this PR should be complete.

**Comment by RaeedA** [comment]
Just merged changes from main to the branch, working on the test-registry issue now.

**Comment by RaeedA** [comment]
Just updated it! All errors in test_registry.py are gone now.

**Comment by RaeedA** [comment]
Also, I just noticed that make test is currently broken. Any idea why?

**Comment by mataton** [comment]
@RaeedA Are you doing `make test` on a windows machine? That won't work. You can try `python -m skbio.test` on a windows machine and it will do the same thing as `make test`. If it is broken on linux or mac then I'm not sure why without looking into it more.

**Comment by RaeedA** [comment]
@mataton for me, make test is broken on both Windows and Mac, running python -m unittest works on Windows but not Mac. I can make an issue soon with screenshots.

**Comment by mataton** [comment]
More context on `make` on windows can be found [here](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows).

**Comment by mataton** [comment]
@RaeedA I would make an issue if it persists. `make test` is working for me on linux right now and on windows always just used `python -m skbio.test` and that is working.

**Comment by RaeedA** [comment]
Ok it seems like the issue is only present on this branch, I'm not sure why though. I've attached an image of the issue below.
Screen Shot 2024-06-28 at 2 15 36 PM

**Comment by mataton** [comment]
@RaeedA Which version of biom do you have installed in that environment? Some recent changes were made to that package which affected those functions so that might be it. You can do `conda update --all` in that environment to update all packages, including biom. Or just update biom individually if you prefer to do that.

**Comment by qiyunzhu** [comment]
@RaeedA It might be useful to re-setup the scikit-bio dev environment. Recently we had some updates of the dependencies.

**Comment by RaeedA** [comment]
I'll give that a go, thank you!

**Comment by qiyunzhu** [comment]
Looks like all tests have passed. Let's merge! @RaeedA Thank you for your timely contribution!!

**Pull request merged**
