### PR TITLE
Refactoring plotting functionality

### PR DESCRIPTION
**Pull request by qiyunzhu**
Following issue #1895 and offline discussion, I refactored the plotting functionality in scikit-bio.

Currently there are two classes that can plot: `DistanceMatrix` and `OrdinationResults`. Each of them has its independent plotting functions. I created a new class: `PlottableMixin` to provide some general plotting behaviors for both of them and future additions.

IPython is no longer required. However, scikit-bio still supports displaying plots in Jupyter. This includes when the user types the name of an instance (like `dm`).

Matplotlib becomes an optional dependency. Scikit-bio can function without it. It attempts to import it when plotting. This behavior is similar to other libraries discussed in #1895 . This increases deployability of scikit-bio, especially in HPC or restricted systems where there is no graphics.

Very minor fixes were made to `OrdinationResult.plot` to reflect updated Matplotlib usages.

***

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by mortonjt** [comment]
Hi, I'll need to test this plotting functionality. Some snapshots posted here would help ensure reproducibility.

Futhermore, this is probably a good time to start putting in plotting unittests -- it is not a bad idea to extract coordinates, x/y-ticklabels, titles, etc from the matplotlib objects and validate them.   Matplotlib has a fairly extenstive unittesting library, so it may be good enough to validate the underlying matplotlib objects.  This is what Seaborn does, and we did adopt this strategy for the plotting functionality in gneiss (see [here](https://github.com/biocore/gneiss/blob/master/gneiss/plot/tests/test_heatmap.py) for an example)

**Comment by qiyunzhu** [comment]
@mortonjt Good point! The current PR only concerns refactoring the plotting backend (i.e, when to import matplotlib) and frontend (i.e., how to bring graph to screen). The actual plotting functions are untouched. How about we merge this one, then work on testing individual plotting functions?

Re: reproducibility: You can following the scikit-bio [documentation](https://scikit.bio/docs/latest/generated/skbio.stats.ordination.OrdinationResults.plot.html) to see if you get the same plots as I did:

image
image

**Comment by mortonjt** [comment]
Ok great! In that case I’m OK with this PR as is

**Comment by mortonjt** [comment]
Hi, after some offline discussion, I think this pull request is a minor refactor and keeps the existing functionality intact. @qiyunzhu should we get another reviewer on this before merging?

**Comment by qiyunzhu** [comment]
@mortonjt Thanks! Daniel also read it and commented on the checklist offline, although not on the plotting functionality itself. @wasade do you have some comments to share or should we just merge?

**Pull request merged**
