### PR TITLE
Improving alpha diversity metrics

### PR DESCRIPTION
**Pull request by qiyunzhu**
Please complete the following checklist:

This is an ongoing effort but I think I need to make a checkpoint here. Basically I was reviewing all alpha diversity metrics currently implemented in scikit-bio. What I did include:

- Added definitions, common denotions, original publications, and any useful notes on each metric.
- Dealt with edge cases such that the result of an empty sample will be zero, instead of nan or zero division warning.
- Replaced "OTU" with "species" as the former is bit historical and specific.

Further improvements will follow, but we should move forward from here.

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by mataton** [comment]
@qiyunzhu I read through the code a few times and built the docs locally. Everything looks good and the documents render correctly. One question I have is the use of capital letters such as `N` and `S` for variable names. Is this to denote the difference between `N` being the total number of individuals in the sample vs `n` being the number of individuals in a particular OTU? If so, I think it's fine to leave it. Otherwise it might be better from a stylistic standpoint to keep them lowercase, as they are, in general, lowercase in the rest of the codebase.

**Comment by qiyunzhu** [comment]
@mataton Thank you very much for thoroughly reading and thinking of this PR!

Capital letters like `N` and `S` are usually used to describe the entire population, whereas small letters like `n` are for individual species or any kind of discrete groups within a population. These denotions are common in literature of community ecology as well as other fields.

In engineering however, capital letters usually denote a vector whereas small letters denote a scalar.

**Comment by qiyunzhu** [comment]
@mortonjt Would you like to merge? Thanks!

**Comment by mortonjt** [comment]
Thanks @mataton !

**Pull request merged**
