### PR TITLE
Ruff Integration

### PR DESCRIPTION
**Pull request by mataton**
# Ruff Integration
This pull request introduces the integration of [Ruff](https://github.com/astral-sh/ruff) into our project as a linter and formatter, per the suggestion of @wasade. It outlines initial configurations, discusses the possibility of reformatting the entire project, and presents options for incorporating Ruff into our workflow.

## Configuring Ruff
Ruff [configurations](https://docs.astral.sh/ruff/configuration/), currently basic, are specified in the `pyproject.toml` file. We can discuss and refine these settings. Current configurations include line length, indent width, target Python version, exclusion of specific files, adoption of pycodestyle [rules](https://docs.astral.sh/ruff/rules/), and preferences for single quotes and spaces for indentation.

## Reformatting entire codebase
The question of reformatting `skbio` entirely using Ruff is open for discussion, as it would modify the structure of most files. Ruff is intended as a drop-in replacement for [Black](https://github.com/psf/black) which itself is widely used. @qiyunzhu has reviewed this PR and supports the adoption of Ruff's default formatting, including a line-width of 88 instead of 79. Below are some examples of Ruff's autoformatting. 

This...
```python
    def _set_amino_acids(self, amino_acids):
        amino_acids = Protein(amino_acids)

        if len(amino_acids) != self._num_codons:
            raise ValueError("`amino_acids` must be length %d, not %d"
                             % (self._num_codons, len(amino_acids)))
        indices = (amino_acids.values == b'M').nonzero()[0]
        if indices.size < 1:
            raise ValueError("`amino_acids` must contain at least one M "
                             "(methionine) character")
        self._amino_acids = amino_acids
        self._m_character_codon = self._index_to_codon(indices[0])
```
...becomes this.
```python
    def _set_amino_acids(self, amino_acids):
        amino_acids = Protein(amino_acids)

        if len(amino_acids) != self._num_codons:
            raise ValueError(
                '`amino_acids` must be length %d, not %d'
                % (self._num_codons, len(amino_acids))
            )
        indices = (amino_acids.values == b'M').nonzero()[0]
        if indices.size < 1:
            raise ValueError(
                '`amino_acids` must contain at least one M ' '(methionine) character'
            )
        self._amino_acids = amino_acids
        self._m_character_codon = self._index_to_codon(indices[0])
```

This...
```python
def _chao_confidence_no_singletons(n, s, zscore=1.96):
    """Calculates confidence bounds for chao1/chao2 in absence of singletons.

    Uses Eq. 14 of EstimateS manual.

    `n` is the number of individuals and `s` is the number of OTUs.

    """
    P = np.exp(-n / s)
    return (max(s, s / (1 - P) - zscore * np.sqrt((s * P / (1 - P)))),
            s / (1 - P) + zscore * np.sqrt(s * P / (1 - P)))

```
...becomes this.
```python
def _chao_confidence_no_singletons(n, s, zscore=1.96):
    """Calculates confidence bounds for chao1/chao2 in absence of singletons.

    Uses Eq. 14 of EstimateS manual.

    `n` is the number of individuals and `s` is the number of OTUs.

    """
    P = np.exp(-n / s)
    return (
        max(s, s / (1 - P) - zscore * np.sqrt((s * P / (1 - P)))),
        s / (1 - P) + zscore * np.sqrt(s * P / (1 - P)),
    )
```
And this...
```python
        pair_member_1_len, pair_member_2_len = _pair_members_to_new_node(
            dm, idx1, idx2, disallow_negative_branch_length)
        # define the new node in newick style
        node_definition = "(%s:%f, %s:%f)" % (pair_member_1,
                                              pair_member_1_len,
                                              pair_member_2,
                                              pair_member_2_len)
        # compute the new distance matrix, which will contain distances of all
        # other nodes to this new node
        dm = _compute_collapsed_dm(
            dm, pair_member_1, pair_member_2,
            disallow_negative_branch_length=disallow_negative_branch_length,
            new_node_id=node_definition)

    # When there are three distances left in the distance matrix, we have a
    # fully defined tree. The last node is internal, and its distances are
    # defined by these last three values.
    # First determine the distance between the last two nodes to be joined in
    # a pair...
    pair_member_1 = dm.ids[1]
    pair_member_2 = dm.ids[2]
    pair_member_1_len, pair_member_2_len = \
        _pair_members_to_new_node(dm, pair_member_1, pair_member_2,
                                  disallow_negative_branch_length)
    # ...then determine their distance to the other remaining node, but first
    # handle the trival case where the input dm was only 3 x 3
    node_definition = node_definition or dm.ids[0]
    internal_len = 0.5 * (dm[pair_member_1, node_definition] +
                          dm[pair_member_2, node_definition] -
                          dm[pair_member_1, pair_member_2])
    if disallow_negative_branch_length and internal_len < 0:
        internal_len = 0

    # ...and finally create the newick string describing the whole tree.
    newick = "(%s:%f, %s:%f, %s:%f);" % (pair_member_1, pair_member_1_len,
                                         node_definition, internal_len,
                                         pair_member_2, pair_member_2_len)

    # package the result as requested by the user and return it.
    return result_constructor(newick)
```
...becomes this.
```python
        pair_member_1_len, pair_member_2_len = _pair_members_to_new_node(
            dm, idx1, idx2, disallow_negative_branch_length
        )
        # define the new node in newick style
        node_definition = '(%s:%f, %s:%f)' % (
            pair_member_1,
            pair_member_1_len,
            pair_member_2,
            pair_member_2_len,
        )
        # compute the new distance matrix, which will contain distances of all
        # other nodes to this new node
        dm = _compute_collapsed_dm(
            dm,
            pair_member_1,
            pair_member_2,
            disallow_negative_branch_length=disallow_negative_branch_length,
            new_node_id=node_definition,
        )

    # When there are three distances left in the distance matrix, we have a
    # fully defined tree. The last node is internal, and its distances are
    # defined by these last three values.
    # First determine the distance between the last two nodes to be joined in
    # a pair...
    pair_member_1 = dm.ids[1]
    pair_member_2 = dm.ids[2]
    pair_member_1_len, pair_member_2_len = _pair_members_to_new_node(
        dm, pair_member_1, pair_member_2, disallow_negative_branch_length
    )
    # ...then determine their distance to the other remaining node, but first
    # handle the trival case where the input dm was only 3 x 3
    node_definition = node_definition or dm.ids[0]
    internal_len = 0.5 * (
        dm[pair_member_1, node_definition]
        + dm[pair_member_2, node_definition]
        - dm[pair_member_1, pair_member_2]
    )
    if disallow_negative_branch_length and internal_len < 0:
        internal_len = 0

    # ...and finally create the newick string describing the whole tree.
    newick = '(%s:%f, %s:%f, %s:%f);' % (
        pair_member_1,
        pair_member_1_len,
        node_definition,
        internal_len,
        pair_member_2,
        pair_member_2_len,
    )

    # package the result as requested by the user and return it.
    return result_constructor(newick)
```

## Workflow
Ruff can be [employed](https://docs.astral.sh/ruff/integrations/) as a pre-commit hook and/or via Github Actions.

### Ruff as a pre-commit hook
Configured to run with the --fix option, Ruff's [pre-commit](https://github.com/pre-commit/pre-commit) hook performs safe fixes automatically. Developers can opt to use this by installing pre-commit, running `pre-commit install` from the project's root, and then committing changes.

### Ruff as a github action
Ruff can replace Flake8 in Github Actions or be used for more sophisticated tasks, such as auto-committing suggested changes. However, the latter approach may involve some complexity, as seen with the [git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action).

## Suggestion
Choosing the implementation strategy requires discussion and consensus. **The suggested approach is to use Ruff's linter and formatter as a pre-commit hook and replace Flake8 with Ruff as our linter in the Github workflow**. This balances simplicity and effectiveness. Further refinements can be made as needed.

Note that the code as written currently in this PR does not reflect this suggested approach. Rather, the code presented here is intended as an illustration of how Ruff would be integrated to function as both a pre-commit hook and as a github action with automatic commits enabled. 

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/scikit-bio/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/scikit-bio/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by wasade** [comment]
This is absolutely wonderful, thank you @mataton! Doing a specific review right now.

I would be in favor of automating the formatting, but I don't have an opinion if that is via pre-commit or other mechanism. If other projects in the scientific ecosystem have adapted ruff, which I think is the case, then I think we should consider using the approach they take for style. 

We spend so much time on style stuff -- it would be glorious to never think about it again!

**Review by wasade — COMMENTED** [review]
I think this all seems reasonable!

**Comment by mortonjt** [comment]
This is awesome!  I think the pre-commit hook is a good idea -- let's just make sure that the process is straightforward / documented. Pre-commit hooks can get confusing if it requires re-adding files multiple times before pushing.

**Comment by qiyunzhu** [comment]
@wasade Thanks for your comment! @mortonjt Would you like to take a look and share your opinion? Most importantly, this will change our coding style quite significantly. For example, the line width limit will become 88, instead of 79. However, the [Black code style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html) (i.e., the default of Ruff) is now quite popular, and has been adopted by many data science projects, like Pandas, scikit-learn, etc. One advantage of it, as many developers agreed on, is that it eliminates debates on coding style and let people concentrate on more useful things. Therefore, despite that it conflicts with my previous coding habit, I tend to endorse adoption of it to scikit-bio.

**Comment by qiyunzhu** [comment]
@mortonjt You just commented while I was typing :) Thanks! Now we have consensus.

**Comment by mataton** [comment]
Thank you guys! It sounds like we're all in favor of using Ruff's autoformatter and linter as a pre-commit hook instead of a github action. I think it makes sense to use Ruff as a drop-in replacement for Flake8 in our github workflow as well. I'll develop the code further to reflect this preference, and I'll start working on some documentation on how to implement the pre-commit hooks in the most straightforward way.

**Comment by qiyunzhu** [comment]
Hi @mataton What a huge PR! But we know that most are the results of Ruff reformatting. Is this PR ready to be considered for merging (you still have "WIP" in the title)?

**Comment by qiyunzhu** [comment]
@mataton I recall that the Ruff/Black default is to use double quotes over single quotes. But in this PR they all become single quotes. Is there a rationale for this? (I actually prefer single quotes, but I recall that we discussed and had the consensus of adopting the default. If you find multiple other mainstream packages using single quotes, we can revisit this.)

**Comment by mataton** [comment]
@qiyunzhu The standard is to use double quotes, I can make this change easily. It is still WIP because I'd like to create some sort of documentation on how to use the `pre-commit` hooks. I could add this documentation to the `CONTRIBUTING.md` file, unless you think there is a more appropriate place for this to go?

**Comment by qiyunzhu** [comment]
`CONTRIBUTING.md` will be a good place for the relevant documentation!

**Comment by qiyunzhu** [comment]
@mataton and I went through this PR. We think it is good to go!

Note: The documentation still needs to be updated. At present the documentation is quite outdated. A lot needs to be done. I am doing a refreshment in the website branch.

**Pull request merged**
