### PR TITLE
Refactored subsample_counts

### PR DESCRIPTION
**Pull request by qiyunzhu**
This PR rewrote part of `skbio.stat.subsample_counts`. The rationale is provided in #1885 .

Note that it is not yet the ultimate form. It will be further improve after the new NumPy random generator is adopted (see #1886 ).

Note that this change will not affect QIIME 2, which uses `biom.Table.subsample` instead.

***
**Update 2**: for sparse data, the following modification is more efficient. It extracts the indices of non-zero elements, and rans the core algorithm on them only, then convert the result back to the original shape. Inspired again by @wasade .

```python
def subsample_sparse(counts, n, seed=None):
    rng = np.random.default_rng(seed)
    nonzero = counts[nzidx := np.where(counts != 0)[0]]
    permuted = rng.choice(nonzero.sum(), size=n, replace=False, shuffle=False)
    digits = np.digitize(permuted, np.cumsum(nonzero))
    idx, freqs = np.unique(digits, return_counts=True)
    result = np.zeros_like(counts)
    result[nzidx[idx]] = freqs
    return result
```

As I found during the test, most memory consumption was involved in the overhead of getting non-zero indices and writing dense arrays. The core algorithm is quite efficient in both speed and memory usage.

Benchmarks:

1. The HMP2 dataset (10614 features by 1569 samples, density = 0.215), ran on an AMD Ryzen 9 6900HX CPU:

```
           wall time    peak memory
unpacking:    10.5  s   424,044,953
binning:       1.34 s   134,956,259
sparse:        1.24 s   134,967,990
prefilter:     1.18 s    29,144,285
biom *:        1.26 s   101,249,698
```

2. The EMP dataset (317314 features by 22811 samples, density = 0.00317), ran on two Intel Xeon Platinum 8358 CPUs:

```
             wall time      peak memory
unpacking:  didn't run
binning:      2min 24s   57,913,710,757
sparse:       1min 48s   57,911,498,675
prefilter:      27.9 s      187,892,256
biom *:       1min  1s    1,091,993,551
```

* biom is the latest development version (commit d3f82fe) which has the optimized algorithm. It serves as a reference but not a fair comparison because it operates on a different data structure.

***
**Update**: benchmark results based on the HMP2 WGS dataset classified by Woltka. The feature table has 10614 features by 1569 samples. The data and benchmark script are attached.
[data.tsv.zip](https://github.com/scikit-bio/scikit-bio/files/13273062/data.tsv.zip)
[bench.ipynb.zip](https://github.com/scikit-bio/scikit-bio/files/13273063/bench.ipynb.zip)

The original version discussed in #1885 :

```python
def subsample_unpack(counts, n, seed=None):
    rng = np.random.default_rng(seed)
    unpacked = np.repeat(np.arange(counts.size), counts)
    permuted = rng.choice(unpacked, size=n, replace=False, shuffle=False)
    idx, freqs = np.unique(permuted, return_counts=True)
    result = np.zeros_like(counts)
    result[idx] = freqs
    return result
```

The new version inspired by @wasade . It avoids unpacking which is memory intensive.

```python
def subsample_bin(counts, n, seed=None):
    rng = np.random.default_rng(seed)
    choices = rng.choice(counts.sum(), size=n, replace=False, shuffle=False)
    permuted = np.digitize(choices, np.cumsum(counts))
    idx, freqs = np.unique(permuted, return_counts=True)
    result = np.zeros_like(counts)
    result[idx] = freqs
    return result
```

Results:
`subsample_unpack`: Wall time: 24.9 s. Peak memory: 406,433,133.
`subsample_bin`: Wall time: 3.36 s. Peak memory: 266,910,395.
`skbio.stats.subsample_counts` as of v0.5.8: Wall time: 8min 39s. Peak memory: 696,843,704.
`biom.Table.subsample` as of v2.1.15: Wall time: 7min 36s. Peak memory: 444,404,878.

(Note: it may not be completely fair to include biom, which deals with a different data structure.)

Therefore, the new version is advantageous in both wall time and memory usage.

Comparison of distributions of subsampled counts of one sample, showing high overlap.

image

***

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [ ] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by mortonjt** [comment]
This is *great* -- especially since it removes all of that extra cython code

**Comment by qiyunzhu** [comment]
@mortonjt Thanks! @wasade What do you think? Especially because this is relevant to the same function in biom-format.

**Comment by mortonjt** [comment]
Hi @qiyunzhu see my comment here : https://github.com/scikit-bio/scikit-bio/pull/1889

I think we need another test to ensure that the seeds are disjoint

**Comment by qiyunzhu** [comment]
@mortonjt This PR and #1889 do not affect each other. Once both are merged, I intend to create another or a couple of PRs to connect every function that uses random number with the new random number generator.

**Comment by wasade** [comment]
Instead of removing the Cython code, I recommend adopting the revised and optimized approach now taken in BIOM (see https://github.com/biocore/biom-format/pull/935)

**Comment by qiyunzhu** [comment]
@wasade Thanks for the input! The subsampling without unpacking is certainly a big advantage. I read your code but couldn't understand well because I currectly do not have much knowledge of sparse matrix. Specifically, I don't know what is `indptr`. Do you want to suggest a way to move forward?

**Comment by wasade** [comment]
Thanks! The wikipedia page on CSR has historically been pretty good (https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format)). But briefly, intptr represents the start/stop indices in data that correspond to a given row of data. The biom implementation is designed for many samples not a single sample, so that can be worked around.

**Comment by qiyunzhu** [comment]
@wasade Thank you! Based on your inspiration, I came up with a new, simple NumPy solution that doesn't require unpacking:

```python
def subsample_without_replacement(counts, n):
        permuted = np.random.choice(counts_sum, size=n, replace=False)
        digitized = np.digitize(permuted, np.cumsum(counts))
        idx, freqs = np.unique(digitized, return_counts=True)
        result = np.zeros_like(counts)
        result[idx] = freqs
```

Note that the `np.random.choice` (including the new `np.random.Generator.choice`) step still requires generating `np.arange(counts_sum)` under the hood. Therefore, memory-wise it is not that efficient either. In my test, this entire function uses 50% memory compared with my the previous version.

I noticed that [your code](https://github.com/biocore/biom-format/blob/d3f82fe666c18bb30cbf571a7e114042308a326c/biom/_subsample.pyx#L99) also has this step. Therefore, I suspect that the memory issue also persists.

I think that a better solution may be using `np.random.randint` (or the new `np.random.Generator.integers`), which does not require unpacking (tested and working). However, unfortunately, it does not support `replace=False`. Therefore, perhaps a way is to let it return more than `n` numbers and keep only unique values. If the number of unique values falls below `n`, then do another round of `randint` until there are sufficient. This apparently is complicated.

**Comment by qiyunzhu** [comment]
@wasade Not really. Using the new `np.random.Generator.choice` with `shuffle=False` significantly reduces memory usage. I think that it doesn't require unpacking. Therefore, problem solved! I would suggesting merging this PR as well as #1889 . Then we can add the new random generator to further improve this function (and others).

**Comment by sfiligoi** [comment]
@qiyunzhu Can you provide some benchmark numbers for some sizable inputs?
I.e. EMP or larger?
Also, some benchmark numbers for a high-count (>4G) input would also be very valuable.

Both CPU-wise and memory wise, and comparing to the current master branch?

**Comment by qiyunzhu** [comment]
@sfiligoi Sure! Benchmark results provided in the main thread. The input dataset is pretty large in the real world, but not as large as the metrics you suggested. If you have them, you are welcome to test them too!

**Comment by wasade** [comment]
@qiyunzhu @sfiligoi and I had an out-of-band discussion on this. We have merged but unreleased code in BIOM, which was not part of the benchmark. When incorporated, it is quite a bit faster and less memory. This suggests the revised implementation in BIOM `master` should be considered for implementation here.

Screen Shot 2023-11-06 at 2 55 13 PM
Screen Shot 2023-11-06 at 2 55 36 PM

**Comment by qiyunzhu** [comment]
This is being addressed in #2016 by @wasade . So closing the current PR.

**Pull request closed without merging**
