### PR TITLE
Categorized composition functions

### PR DESCRIPTION
**Pull request by qiyunzhu**
Organized functions under `skbio.stats.composition`. Like this:

view

***

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [ ] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by mortonjt** [comment]
I like it, but am confused about the zero handling. Shouldnt we only have 1 function?

Arithmetics ->  Arithmetic operations

there are missing references like aldex2

vlr functions should belong to a miscellaneous section. May want consider putting zero handling methods under there as well.

**Comment by qiyunzhu** [comment]
@mortonjt Thanks for the comments!

`multi_replace` is just an abbreviation for `multiplicative_replacement`, which is too long. I saw other [packages](https://www.rdocumentation.org/packages/zCompositions/versions/1.5.0-4/topics/multRepl) call it `multRepl`. I think that "zero handling" is a topic that average users would be interested in. What do you think?

I don't understand the purpose of `vlr` as its documentation is very brief. It will be helpful if you can briefly describe it.

**Comment by mortonjt** [comment]
Right, but I thought we agreed on just 1 function rather than 2 for zero handling. I’m OK with keeping that subheading as is

VLR is for variance log-ratio. It is used for correlation analysis (ie microbe-microbe correlation). So maybe a good subheading is Correlation

**Review by mortonjt — APPROVED** [review]
LGTM thanks @qiyunzhu

**Comment by qiyunzhu** [comment]
Hi @mortonjt I addressed your other comments. Regarding the abbreviation of `multiplicative_replacement`, I did discussed with you before making the change (#1988). There are multiple places in skbio that functions have abbreviations (such as `lowest_common_ancestor` => `lca`). It will be the best if we can let long and short names of the same function stay in the same line of the documentation, like

`multi_replace` | `multiplicative_replacement`: Replace all zeros with small non-zero values.

But so far I haven't figured out a way to let Sphinx do that in a toctree. I can spend some extra time in the near future for this.

Regarding the citation of ALDEx2, I think that it exists inside the [documentation page](https://scikit.bio/docs/latest/generated/skbio.stats.composition.dirmult_ttest.html) of the`dirmult_ttest` function. Same for ANCOM. Do you think we should leverage them to the main page of "composition"?

**Comment by mortonjt** [comment]
Thanks @qiyunzhu I think this is fine as is.

**Pull request merged**
