### PR TITLE
Fix cython zero division errors on Windows

### PR DESCRIPTION
**Pull request by mataton**
This PR fixes zero division errors which were happening in `skbio/metadata/_intersection.pyx`. The fix is fairly straightforward, just ensure that the random numbers used can never lead to division by zero.

The value chosen for `RAND_MAX` is the lowest possible value from its standard definition. See [here](https://en.cppreference.com/w/cpp/numeric/random/RAND_MAX) for more details.

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [ ] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Review by qiyunzhu — COMMENTED** [review]
This is effective but sounds bit scary. Doesn't Python have binomial distribution under `scipy.stats.binom`? @mortonjt

**Comment by qiyunzhu** [comment]
I think @mataton 's solution is right in logic, but just needs a small tweak. How about:

```
self.priority = ceil(nlog * log(-1.0/(1.0 * rand()/(RAND_MAX + 1) - 1)))
```

This will ensure that `rand()/(RAND_MAX + 1)` is always < 1.

Actually, I think the original code doesn't enforce that and is probably not correct. The test passed in Linux simply because `RAND_MAX` is large enough such that zero division _happened_ to not happen. But in Windows it is smaller. @mortonjt

**Comment by qiyunzhu** [comment]
Here is some discussion: https://stackoverflow.com/questions/6218399/how-to-generate-a-random-number-between-0-and-1

**Comment by mataton** [comment]
@qiyunzhu Your solution works! I've pushed the commits so we should be able to merge if everyone thinks this is a good solution.

**Review by qiyunzhu — APPROVED** [review]
Great job @mataton !

**Pull request merged**
