### PR TITLE
Implemented augmented assignments

### PR DESCRIPTION
**Pull request by mataton**
Implemented augmented assignments proposed in issue #1789, except for those changes which would cause dtype errors. 

Please complete the following checklist:

* [X] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [X] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [ ] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@mataton Thank you for submitting your first PR to scikit-bio! This looks great! I have some comments which hopefully will be helpful to you:

1. As you can see, the build failed. Specifically, when you replaced

```python
mat = mat / mat.sum(axis=1, keepdims=True)
```

With:

```python
mat /= mat.sum(axis=1, keepdims=True)
```

It said:

```
E       numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

This is because `mat` is an integer matrix. NumPy is perfectly fine with dividing an integer matrix by another and getting a float matrix. However, by using `/=`, NumPy assumes that that data type of the matrix will remain the same, i.e., integer. This caused the error.

Therefore, I would suggest that we revert this particular case.

2. Another suggestion is that you document the work you did in the PR. You can say that you implemented augmented assignments in some cases, which was suggested by @user_name in #issue_number. Thank you for their suggestion. Note that the #issue_number will link to the original issue.

Thank you! Looking forward to your update.

**Review by qiyunzhu — APPROVED** [review]
@mataton Thanks! This looks good now. Let's merge.

**Comment by elfring** [comment]
>NumPy is perfectly fine with dividing an integer matrix by another and getting a float matrix. However, by using `/=`, NumPy assumes that that data type of the matrix will remain the same, i.e., integer.

How do you think about to reduce any risks for corresponding confusion by choosing different variable names? :thinking:

**Comment by elfring** [comment]
Thanks for a few adjustments of implementation details.

**Pull request merged**
