### PR TITLE
Minor edits of embedding

### PR DESCRIPTION
**Pull request by qiyunzhu**
This PR did some minor edits to the embedding functionality. Unit test coverage is upped. Entries were added to documentation. Wording in documentation and error messages were adjusted. Unused imports were removed. Unit test methods were adjusted. Some minor issues (like redundant copy of np.array, unwanted file writing during unit test) were fixed.

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [ ] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by mortonjt** [comment]
Hi @qiyunzhu thanks for correcting the documentation. This pull request is looking pretty good. I'll provide detailed comments by the end of the day.

**Comment by qiyunzhu** [comment]
@mortonjt Thanks! Additional note: unit-test coverage is 100% in my local environment. Not sure why codecov doesn't honor that. You are right that we need to look into codecov.

**Comment by qiyunzhu** [comment]
@mortonjt Now I figured out why code coverage dropped: A `tests` directory needs an empty `__init__py` in it in order to be included in the package. A `tests/data` directory needs to be noted in `setup.py` in order to be included. Once these two things are added, the coverage is back.

**Comment by mortonjt** [comment]
Great! Merge?

**Pull request merged**
